theme: jekyll-agency
/*
title      : Your Awesome Website
email      : your-email@example.com #this is also the email contact forms will go to
description: "Site description"
author     : Your Name

  portfolio:
*/
markdown: kramdow
